name: Build and Push Docker image

on:
  push:
    branches:
      - main   # main branch ကို push လိုက်တာနဲ့ run
  workflow_dispatch: {}  # လိုချင်ရင် Manual runလည်း ရ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/n4sshx:latest
          platforms: linux/amd64
